### ISSUE TITLE
Handle orientation changes

### ISSUE THREAD

**Issue by jlelse** [ncapdevi/FragNav#10]
Is there a possibility to save the current state and the current fragment etc. when onSaveInstanceState is called in the activity?

**Comment by two1stnamz** [comment]
Hey! Checkout my pull request here:

https://github.com/ncapdevi/FragNav/pull/12

**Comment by ncapdevi** [comment]
Pull request #12  fixes this. I'll upload an updated version sometime in the next day or so.

**Comment by jlelse** [comment]
Thanks! Now I think my project is near to go live...
