### ISSUE TITLE
Enable/disable backstack in runtime

### ISSUE THREAD

**Issue by ahgpoug** [ncapdevi/FragNav#104]
Is there any option to disable backstack feature in runtime? I mean, to keep backstack for current tab and restore root fragment when I leave it.
I want to have an option in settings that allows user to enable/disable it. I've tried to do it by myself by clearing backstack, pushing fragments to the 0 instance and some other options, but nothing helped.
Perhaps issue #93 can do what I want to.
Thanks in advance.

**Comment by ncapdevi** [comment]
@ahgpoug I'm having a little trouble fully grasping the use-case that you're describing here. Could you give me a bit more a concrete example of how you're hoping it would work?

**Comment by ahgpoug** [comment]
@ncapdevi thanks for your reply. 
I want to keep a backstack for active (current) tab and clear it after I switch to another tab. In short, not to keep backstack for inactive tabs and start from root fragment when I switch back to it. 
Sorry, have no idea how to describe it in more detail.

**Comment by ncapdevi** [comment]
@ahgpoug  Nope, that makes sense, thanks for the description.  That being said, shouldn't you be able to clear the stack when you switch to a new tab? By that I mean, let's assume you're on stack A, when your user presses on a button to switch to Stack B, you first clear the current stack and then switch?  Does that not work?

**Comment by ahgpoug** [comment]
@ncapdevi my bad. I've tried at least 3 ways to achieve this, but missed the most obvious.

    bottomNavigationView.setOnTabSelectListener(tabId -> {
            if (!App.INSTANCE.isBackstackEnabled())
                navController.clearStack();

            switch (tabId) {
                /* smth */ 
            }
    });

did the trick. Sorry about this silly question. I really need to be more focused. 
Thanks again for reply and great job you did, working on this library.

**Comment by ncapdevi** [comment]
Not a problem at all. Sometimes it just takes a second person to look at it from a different perspective for a second to help clear things up. Glad it worked out.
