### ISSUE TITLE
Updating to 2.3.0+ breaks CollapsingToolbar

### ISSUE THREAD

**Issue by chrjsorg** [ncapdevi/FragNav#108]
Hi,

first of all, thanks for your library. It worked great so far! :)

I just updated the library in my app from 2.2.3 to 2.40 (also tried 2.3.0) and I think there is a problem with `AppBarLayout` + `CollapsingToolbarLayout`

Context:
I have a Fragment which has its own `AppBarLayout` which looks like [this](https://gist.github.com/chrjsorg/ebcc22f1556bd8cb3d571630f72a95ac)

It should look like this (expanded, collapsed):
![bildschirmfoto 2018-01-04 um 15 45 50](https://user-images.githubusercontent.com/441326/34568621-ab9e485e-f166-11e7-80b3-a7c0a0a589f3.png)
![bildschirmfoto 2018-01-04 um 15 46 00](https://user-images.githubusercontent.com/441326/34568622-af8f6664-f166-11e7-8df4-f8dad6641d37.png)

But since version 2.3.0 it looks like this (expanded, collapsed):
![bildschirmfoto 2018-01-04 um 15 48 51](https://user-images.githubusercontent.com/441326/34568801-384cd84c-f167-11e7-834a-ea1990027016.png)
![bildschirmfoto 2018-01-04 um 15 48 59](https://user-images.githubusercontent.com/441326/34568803-3a112ae8-f167-11e7-9717-54481ae686ef.png)

Do you have an idea for this?

Cheers, 
 Chris

**Comment by ncapdevi** [comment]
@chrjsorg I can't imagine any way that the library would be responsible for causing this issue, and it would be happening weather you used the Android backstack, or any other library. The only thing FragNav does it take in a single view ID for your layout, and use that as a container for transactions (the same way the Android backstack would). My guess is something else changed in your project or in one of your libraries (possibly an update to the support library?). However, if you can point it to something relevant within the library, I would be happy to help.
