### ISSUE TITLE
Make isRootFragment method better

### ISSUE THREAD

**Issue by Monster-king** [ncapdevi/FragNav#116]
Now isRootFragment doing more boilerplate works which not need (like copying stack etc.). make it like:
```
public boolean isRootFragment() {
        Stack<Fragment> stack = mFragmentStacks.get(mSelectedTabIndex);

        return stack == null || stack.size() == 1;
    }
```

**Comment by ncapdevi** [comment]
Good call. Fixed here https://github.com/ncapdevi/FragNav/commit/181c5615fa33e1314be9a7c088eb5b6ab9117d43
