### ISSUE TITLE
How to save scroll position in Recycler view Fragment in Bottom Nav

### ISSUE THREAD

**Issue by henryagyei** [ncapdevi/FragNav#120]
I have managed to save and restore the last fragment but when I implement a recycler view in one of my fragments I am not able to store the current scroll position of that fragment. 
What should I be using if only one of my tabs is a recycler view which I need to retain its position and ensure also that the data is not being reloaded from my server more than once.

thanks
henry

**Comment by ncapdevi** [comment]
Outside the scope of this library
https://stackoverflow.com/questions/28236390/recyclerview-store-restore-state-between-activities
