### ISSUE TITLE
Issues regarding pendingTransactions

### ISSUE THREAD

**Issue by ncapdevi** [ncapdevi/FragNav#125]
Discussion thread for this issue. The use-cases and expectations should be clearly defined, as the current system has flaws and is easy to create problems.

https://github.com/ncapdevi/FragNav/projects/2

**Comment by ncapdevi** [comment]
https://github.com/ncapdevi/FragNav/releases/tag/3.0.0-RC

**Comment by kagile** [comment]
@ncapdevi Is there any update on final 3.0 release?
