### ISSUE TITLE
saved instance state has an error and can't compile

### ISSUE THREAD

**Issue by TimJung** [ncapdevi/FragNav#13]
Specifically this occurs on line 84 in the BottomTabsActivity and line 76 in the NavDrawerActivity.

What is the purpose of this? And why is it broken in these places in the sample app? Commenting them out allows the app to still run.

**Comment by two1stnamz** [comment]
The gradle dependency for this library has not been updated with a new build yet. As a temporary fix, in the sample project's build.gradle file comment out this line

compile 'com.ncapdevi:frag-nav:1.0.2'

and uncomment this line

compile project(':frag-nav')
