### ISSUE TITLE
FragNav3.0

### ISSUE THREAD

**Issue by ncapdevi** [ncapdevi/FragNav#131]

**Comment by artem1989** [comment]
When release of new version with functionality in kotlin branch approximately expected?

**Comment by ncapdevi** [comment]
@artem1989 I would say in the next couple weeks I'd like to get something out there.

**Comment by gildor** [comment]
Any updates? Want to use DETACH mode for our app.
I and my team can help and contribute if you need some help and you have some blockers for release

**Comment by ncapdevi** [comment]
@gildor  @artem1989 a you can try https://github.com/ncapdevi/FragNav/releases/tag/3.0.0-RC

**Comment by rhonyabdullah** [comment]
Hello, i read this latest [commit](https://github.com/ncapdevi/FragNav/commit/cc3087da647459a21c6bf68cce74ab36d60e9af0) on master was merged 2 months ago, is this production ready ?

**Comment by sepiddezh** [comment]
When is the final version 3 released?

**Comment by tcqq** [comment]
+1

**Comment by mateherber** [comment]
Has been released, this can be closed
