### ISSUE TITLE
Can't change tag of fragment

### ISSUE THREAD

**Issue by enizbilgin** [ncapdevi/FragNav#135]
I not change tag, Sometimes it throws this error.  
Caused by java.lang.IllegalStateException : **Can't change tag of fragment**

**Comment by ncapdevi** [comment]
Hmm, my guess is that you're trying to reuse the same instance of a fragment for multiple pushes? Is that possible? https://stackoverflow.com/questions/16345129/java-lang-illegalstateexception-cant-change-tag-of-fragment Doesn't sound like an issue with the library.

**Comment by cjmaroney01** [comment]
I am having this same issue, and I am pretty sure that I am not pushing the same instance of a fragment and also that I am not trying to access a null fragment.....we are using 2.4.0 though, which is older...... @enizbilgin, did you ever figure out the issue on your end?
