### ISSUE TITLE
Error:Execution failed for task ':frag-nav:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug'. > java.lang.RuntimeException: java.util.zip.ZipException: duplicate entry: com/ncapdevi/fragnav/BuildConfig.class

### ISSUE THREAD

**Issue by asshyy-ktz** [ncapdevi/FragNav#139]
Error:Execution failed for task ':frag-nav:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug'.
> java.lang.RuntimeException: java.util.zip.ZipException: duplicate entry: com/ncapdevi/fragnav/BuildConfig.class

**Comment by ncapdevi** [comment]
Hmm, could you try a clean and rebuild I'm not sure how you're getting that.
