### ISSUE TITLE
mNavController seems to have incorrect parameters and errors / can't compile

### ISSUE THREAD

**Issue by TimJung** [ncapdevi/FragNav#14]
This happens on line 55 in NavDrawerActivity and on line 39 in BottomTabsActivity. However, simply removing the savedInstanceState parameter altogether from both locations allows the app to compile and run.

What's the purpose of trying to pass in this parameter?

**Comment by two1stnamz** [comment]
The gradle dependency for this library has not been updated with a new build yet. As a temporary fix, in the sample project's build.gradle file comment out this line

compile 'com.ncapdevi:frag-nav:1.0.2'

and uncomment this line

compile project(':frag-nav')

**Comment by kryslylam** [comment]
hi I am facing the same problem and I tried importing the frag-nav into my existing project as a module, changed the dependency of my project to compile the project, but it says plugin 'com.jfrog.bintray' not found. how should I link the frag-nav to another project instead of the sample one?

**Comment by two1stnamz** [comment]
In your settings.gradle file, add frag-nav as a dependency like this:

include ':app', ':frag-nav'

Where "app" is your project module

**Comment by kryslylam** [comment]
thank you so much for the quick reply. I checked the file, looks like that automatically appears after I link my 'app' module to 'frag-nav'. but the plugin problem are still there. the whole message is:
Gradle sync failed: Plugin with id 'com.jfrog.bintray' not found.

What I hv done is imported only the 'frag-nav' module from this project (without the sample 'app' module) to my existing project, linked my 'app' module to 'frag-nav'. Is that the problem of importing? or should I try doing the other way round? add a module to this 'FragNav' project?

**Comment by p-fischer** [comment]
I faced the same problems. Please release a new version and do so everytime you push something onto the master branch to not confuse people.

**Comment by ncapdevi** [comment]
Sorry for delay. Library is now up to date, just use compile 'com.ncapdevi:frag-nav:1.1.0' and check out the change log for updates.
