### ISSUE TITLE
Cannot resolve method `eager()`

### ISSUE THREAD

**Issue by aligorji** [ncapdevi/FragNav#144]
Hi

`implementation 'com.ncapdevi:frag-nav:2.4.0'`

....

`.fragmentHideStrategy(FragNavController.DETACH_ON_NAVIGATE_HIDE_ON_SWITCH).eager(true)`

cannot resolve method !!!

**Comment by hannta** [comment]
`eager` is not part of version 2.4.0, it is in `kotlin` branch. Similar issue https://github.com/ncapdevi/FragNav/issues/130

You can use the kotlin branch in your app, adding `compile 'com.github.ncapdevi:FragNav:kotlin-SNAPSHOT'` to your build gradle. You also need to have `maven { url 'https://jitpack.io' }` added in yor app root level gradle, under  `allprojects` - `repositories `.

**Comment by aligorji** [comment]
tnx.
