### ISSUE TITLE
Is there a way to set a transaction listener outside of the builder, or delay initialization?

### ISSUE THREAD

**Issue by erawhctim** [ncapdevi/FragNav#145]
I have an issue with the way the controller is initialized. Basically, I want to set a transaction listener on the builder in order to get those `onTabTransaction` callbacks, but I want to be able to set the listener instance outside of the FragNav controller builder.

My issue really is within the `build` method, which [calls `initialize`](https://github.com/ncapdevi/FragNav/blob/60c0048df6833c78c712a08a58190fb1457fc8e2/frag-nav/src/main/java/com/ncapdevi/fragnav/FragNavController.kt#L77), which eventually calls down into the transaction listener and [calls `onTabTransaction` the first time](https://github.com/ncapdevi/FragNav/blob/60c0048df6833c78c712a08a58190fb1457fc8e2/frag-nav/src/main/java/com/ncapdevi/fragnav/FragNavController.kt#L209). At that point when the listener is called, my listener instance uses some dependency-injected properties that aren't yet available.

My suggestion is: could there be a method on the builder (`Builder.delayInit()` or something) that would indicate to the `build` call to _not_ call initialize and instead rely on the callsite to manually call `initialize` instead? I really just need a way to run some code (Dagger `.inject()` call) in between the builder creation and the `initialize` call on the controller.

I'd happy to get started on a PR and work with you to iterate on it, but I wanted to run the idea by you first to get your thoughts and see if what I'm saying makes any sense (or, better yet, see if you have another suggestion 😄 )

(EDIT: could also be just a parameter on the builder method itself, e.g. `Builder.transactionListener(listener: TransactionListener, delayInit: Boolean = false)`)

**Comment by erawhctim** [comment]
(FYI - I have a change implemented for this [in my fork here](https://github.com/erawhctim/FragNav/commit/b5a3c2abd960e0d83cca8416be8de918ba65e437) and its been working fine)

**Comment by ncapdevi** [comment]
This has been completely revamped for 3.0.0

**Comment by erawhctim** [comment]
@ncapdevi Thanks for the info! is 3.0.0 stable and released already? or still in the middle of the RC phase?
