### ISSUE TITLE
wrong current fragment

### ISSUE THREAD

**Issue by mortezaezzabady** [ncapdevi/FragNav#146]
hi:)
`navController.getCurrentFrag().getClass()` returns previous tab fragment but `navController.getCurrentStack().peek().getClass()` is correct!

**Comment by askarsyzdykov** [comment]
What version do you use?
In 2.3.0 version this bug was fixed

> Modified how public Fragment getCurrentFrag() works. There were previously situations where a fragment had been transacted, and thus was on the stack, but the function was still returning the previous function. This should no longer be the case.

**Comment by mortezaezzabady** [comment]
i'm using v2.1.0, i'll update it, thank you:D
