### ISSUE TITLE
Navigating in fragment

### ISSUE THREAD

**Issue by nominalista** [ncapdevi/FragNav#15]
How to accomplish something like in Google [example](https://www.google.com/design/spec/components/bottom-navigation.html#bottom-navigation-behavior) where they click on Kodaline album in Music tab, and then new view is showing on top without disappearing bottom bar?

**Comment by ncapdevi** [comment]
You can see how this is done using the sample app. Specifically here; https://github.com/ncapdevi/FragNav/blob/master/app/src/main/java/com/ncapdevi/sample/activities/BottomTabsActivity.java
