### ISSUE TITLE
 java.util.EmptyStackException on switchTab

### ISSUE THREAD

**Issue by danpetre** [ncapdevi/FragNav#154]
Using FragNavController with option createEager = false can cause  java.util.EmptyStackException on switching tabs 

On FragNavController.kt private fun switchTabInternal, line 281 

`var tag = fragment.tag ?: fragmentStacksTags[index].peek()`

If createEager is used with false , fragmentStacksTags at index != 0 first time will be empty. Peek on empty Stack will cause  java.util.EmptyStackException

fix:
`var tag = fragment.tag ?: if(fragmentStacksTags[index].empty()) null else fragmentStacksTags[index].peek()`

**Comment by mateherber** [comment]
Thanks for reporting!

I've opened the #156 PR to fix that
