### ISSUE TITLE
Request upgrade to Android X

### ISSUE THREAD

**Issue by tcqq** [ncapdevi/FragNav#161]
@ncapdevi Request to upgrade FragNav to Android X

Because the support library and the androidx library are incompatible, This will lead to multiple errors.
Because support is about to be replaced by androidx. 
![image](https://user-images.githubusercontent.com/10644057/40062547-0b670fc6-588e-11e8-88e0-3082771bacf2.png)
![image](https://user-images.githubusercontent.com/10644057/43682837-0b5a9d18-98b2-11e8-93e3-0de3c7cefbf8.png)

### Refactor AndroidX URL:
https://android-developers.googleblog.com/2018/05/hello-world-androidx.html
https://developer.android.com/studio/preview/features/#androidx_refactoring
https://dl.google.com/dl/android/maven2/index.html

![image](https://user-images.githubusercontent.com/10644057/40062432-c985eadc-588d-11e8-9012-7db9d0fb493d.png)

**Comment by diareuse** [comment]
You're welcome to create pull request for this.
It's simple, you fork this repository. Make changes and then create pull request with your changes. They may not be accepted by the repository owner. However looking at the history of pull requests, it's generally very likely to be accepted.

Have a great day.

**Comment by tcqq** [comment]
@diareuse Thank you for your reply, I will try it when I have time.

**Comment by mateherber** [comment]
If you use the `android.enableJetifier = true` flag in your project gradle plugin will automagically convert all the libraries you use as if it were written for androidX even if the library hasn't yet been migrated.

![image](https://user-images.githubusercontent.com/13942888/43886821-4085d0f8-9bbd-11e8-8a3a-3ee6a3e39672.png)

**Comment by diareuse** [comment]
@mateherber this is true, however as of now it's done in build time, which could significantly increase the total build time. That's why I suspect he's requesting that transition

**Comment by mateherber** [comment]
I'm not sure about the added build time there but I'd wait for migrating any library (at least the release part) until androidX is final

**Comment by diareuse** [comment]
That's for sure, +1 for that.

**Comment by ShurikuS57** [comment]
AndroidX is final.

**Comment by joekaldas** [comment]
So is there a build that supports androidx?

**Comment by mateherber** [comment]
Please watch #178

**Comment by ncapdevi** [comment]
#187 will be released in 3.1.0
