### ISSUE TITLE
 sometimes not show Fragment

### ISSUE THREAD

**Issue by dan085** [ncapdevi/FragNav#163]
I used 

		fragments = new ArrayList<>(5);
				fragments.add(MainActivity_Search_In.newInstance(0, layout_contain_tab));
				fragments.add(MainActivity_List_And_Groups_Url_Word.newInstance(0,  tabs_friends, tabs_group_links, layout_contain_tab));
				fragments.add(MainActivity_List_Friend.newInstance(0, tabs_friends, tabs_group_links, layout_contain_tab));
				fragments.add(Fragment_list_word.newInstance(layout_contain_tab));
				fragments.add( MainActivity_Profile.newInstance(layout_contain_tab));

 mNavController = FragNavController.newBuilder(savedInstanceState, getSupportFragmentManager(), R.id.content_frame)
                    
					.transactionListener(this)
					.rootFragments(fragments)
					.build())
// .rootFragmentListener(this,5)
                    .build();

	mNavController.replaceFragment(fragments.get(2));
but sometimes not show the fragment!

**Comment by sepiddezh** [comment]
When is the final version 3 released?

**Comment by ncapdevi** [comment]
It has been released
