### ISSUE TITLE
Does it support ViewPager?

### ISSUE THREAD

**Issue by MrzAhmadi** [ncapdevi/FragNav#164]
I Would Swipe in Tabs and use a tab layout instead of bottom navigation

**Comment by mateherber** [comment]
I never used it in a viewPager but I'd guess you can support it with this lib. However you'll have to write your own adapter which utilises FragNav properly when changing between "tabs"

**Comment by kagile** [comment]
@ncapdevi @mateherber Is there any update on 3.0 release of this library? We depend on this library but there are many bugs and feature requests.

**Comment by mateherber** [comment]
Hi @kagile, I have rights to administer the repository nor for releasing a new version. I think it still needs several fixes and finalization. Maybe on a fork it is possible to finish up and release.

**Comment by ncapdevi** [comment]
3.0 was released and 3.1.0 will be released shortly.
