### ISSUE TITLE
Fragment that's not added to the back stack

### ISSUE THREAD

**Issue by bagusxxalam** [ncapdevi/FragNav#165]
I have this 3 fragments
Home - Intro - Detail
The intro fragment is like instagram story detail having a countdown timer, and when it's over we move to the detail fragment.
I want to make the intro fragment only appear once, so when user press back button from the Detail fragment it'll back to Home not Intro again, how do i achieve this ?

**Comment by ncapdevi** [comment]
You'd need to replace the fragment when returning to it or re-initialize your fragnav instance.
