### ISSUE TITLE
Is it possible to use FragmentHideStrategy? 

### ISSUE THREAD

**Issue by abayken** [ncapdevi/FragNav#169]
I use 2.4.0 version of library, but didn't find to set `fragmentHideStrategy`. But in sample app, it is possible. So, how to use it? I want to avoid fragment recreation when it is showed. Thanks!

**Comment by mateherber** [comment]
Hi @abayKenzhekhan 

Unfortunately that version was never released as we were preparing for 3.0 release. You may check out the repository and build from 9f7278adc325d8c32e74733995d66f2b98e825ee commit to see a fairly stable state (just make sure you manually call the executePendingTransactions after each call).

Unfortunately I have no ETA for 3.0 :(
