### ISSUE TITLE
clear stack of individual tabs

### ISSUE THREAD

**Issue by shreknitin89** [ncapdevi/FragNav#172]
I tried forking 2.4.0 and added some util methods in FragNavController to accommodate the use case - to clear Tab1 stack completely while I was in Tab2.

But the problem is most of our crashes were due to IllegalStateException while FragNavController try to executePendingTransactions. I saw the previous requests complaining about the same issue on 2.4.0 and moved the executePendingTransactions to after pushing or popping a new fragment but still the crashes appearing after that change.

If you already fixed the issue on 3.0.0 is there an ETA on when that's going to be finalized? I have been waiting for almost 5 months now for the new version.

Second, if you were trying to release 3 sooner could you also include the case I mentioned before - clearing backgrounded tab stack?

**Comment by ncapdevi** [comment]
Fixed in #187  Version 3.1.0
