### ISSUE TITLE
builtin option to hide bottom bar if we are showing detail fragment?

### ISSUE THREAD

**Issue by LOG-TAG** [ncapdevi/FragNav#174]
I need a building method or option hide bottom bar! otherwise custom method with call backs with eventbus or rxbus needed! also deprecated bottombar also should be replaced with  new Material Design Bottom Navigation pattern.

**Comment by Ustimov** [comment]
You may use any bottom bar with this library or even don't use any at all. The library doesn't contain any UI elements, just a way to deal with fragments.
