### ISSUE TITLE
3.0.0: popFragment() with customAnimations not working as expected

### ISSUE THREAD

**Issue by porkyhead** [ncapdevi/FragNav#176]
When using `navController.popFragment()` with FragNavTransactionOptions.customAnimations and specifying enterAnimation, exitAnimation, popEnterAnimation, and popExitAnimation the pop animations have no effect. Instead the enter animations are used.

Example:
`FragNavTransactionOptions.newBuilder()
                .customAnimations(R.anim.slide_in_from_right, R.anim.slide_out_to_left, R.anim.slide_in_from_left, R.anim.slide_out_to_right).build()`

Only `R.anim.slide_in_from_right` and `R.anim.slide_out_to_left` is seen in action when entering AND popping.

Using FragNav 3.0.0 - worked fine on 2.4.0

This is a dealbreaker for me :(

**Comment by mateherber** [comment]
@porkyhead Probably that was my mistake. I'm going to raise a PR which restores the original behaviour

**Comment by mateherber** [comment]
@porkyhead please watch #178

**Comment by ncapdevi** [comment]
Fixed in 3.1.0 #187
