### ISSUE TITLE
PushFragment Language Not Changing

### ISSUE THREAD

**Issue by meMuhammadkamal** [ncapdevi/FragNav#180]
I'm trying to push fragment using:
`mNavController.pushFragment(DetailsFragment.newInstance(), fragNavTransactionOptions);`

but the language isn't changing it stays the default language which is english after pushing  second time the language changes to the selected one.

**Comment by mateherber** [comment]
Hi @meMuhammadkamal,

I don't quite understand what is you problem. Can you give some more context here? What do you mean by language is not changing. Why would you want language to be changed, how do you trigger it. Why language selection is the concern of FragNav?

Can you please add details / code sample?

**Comment by ncapdevi** [comment]
@meMuhammadkamal  please add details, if not, I'll assume this issue can be closed.

**Comment by meMuhammadkamal** [comment]
Sorry for late reply the problem was related to webview not the library.
