### ISSUE TITLE
Clear Root framgents

### ISSUE THREAD

**Issue by javacl** [ncapdevi/FragNav#181]
hi. when i create 5 root fragments then i need to clear them.how i can clear root fragments and remove them from view ?

**Comment by mateherber** [comment]
Hey! There is no built in support to drop all fragments in FragNav however you can do it manually by dropping the reference to fragnavcontroller also clearing the FragmentManager it uses manually (you shouldn't have any other fragment in it anyway as FragNav relies on being the only user of the FragmentManager it is attached to).
