### ISSUE TITLE
rootFragments has private access on com.ncapdevi:frag-nav FragNavController? in java

### ISSUE THREAD

**Issue by hemanth-sp** [ncapdevi/FragNav#184]
`
        //list of fragments
        List<Fragment> fragments = new ArrayList<>(3);

        //add fragments to list
        fragments.add(FirstFragment.newInstance(0));
        fragments.add(SecondFragment.newInstance(0));
        fragments.add(ThirdFragment.newInstance(0));
        //link fragments to container
        fragNavController = new FragNavController(getSupportFragmentManager(), R.id.container);
        fragNavController.rootFragments = fragments; // i am getting error here`

**Comment by webserveis** [comment]
try with:

        fragNavController.setRootFragments(fragments);

**Comment by hemanth-sp** [comment]
error : java.lang.IndexOutOfBoundsException: Can't switch to a tab that hasn't been initialized, Index : 0, current stack size : 0. Make sure to create all of the tabs you need in the Constructor or provide a way for them to be created via RootFragmentListener.

**Comment by malwinder-s** [comment]
Still getting this issue.
