### ISSUE TITLE
How to use setNavigationStrategy in java?

### ISSUE THREAD

**Issue by webserveis** [ncapdevi/FragNav#185]
I need to try change navigation strategy, I use java 8
 
        fragNavController = new FragNavController(getSupportFragmentManager(), R.id.container);
        fragNavController.setRootFragments(fragments);

        fragNavController.setNavigationStrategy(???);
        fragNavController.initialize(MyConstants.INDEX_HOME, savedInstanceState);

**Comment by Ustimov** [comment]
Something like this:

```java
fragNavController.setNavigationStrategy(new UniqueTabHistoryStrategy(
  new FragNavSwitchController()  {
    @Override
    void switchTab(int index, FragNavTransactionOptions transactionOptions) {
      // TODO: some navigate action
    }
  )
);
```
