### ISSUE TITLE
Sample app(UPDATE YOUR LIBRARY)

### ISSUE THREAD

**Issue by bronydell** [ncapdevi/FragNav#19]
Update your sample app and library, because it's without onSaveInstanceState

**Comment by bronydell** [comment]
I got the idea. Author must update lib

**Comment by chawino** [comment]
example for me please

**Comment by johncodeos** [comment]
+1

**Comment by ncapdevi** [comment]
Sorry for delay. Library is now up to date, just use compile 'com.ncapdevi:frag-nav:1.1.0' and check out the change log for updates.
