### ISSUE TITLE
get previous fragment without using TabNavigation

### ISSUE THREAD

**Issue by pishguy** [ncapdevi/FragNav#190]
in my application i dont use any bottom navigation and i want to get previous fragment which i press on Back button on phone or clicking other widgets, how can i get that?

i want to change toolbar text by switching between fragments and onBackPressed button

**Comment by ncapdevi** [comment]
> i want to change toolbar text by switching between fragments and onBackPressed button

This has nothing to do with FragNav. Please keep questions to the scope of the library

**Comment by ncapdevi** [comment]
> in my application i dont use any bottom navigation and i want to get previous fragment which i press on Back button on phone or clicking other widgets, how can i get that?

The question is a little unclear to me, could you clarify?

**Comment by pishguy** [comment]
@ncapdevi for example we are on `HomeFragment`, ok? after switching or pushing other fragment such as `ExampleFragment`, how can i get previous fragment which that was `HomeFragment` after pressing  such as on `BackButton`?

**Comment by ncapdevi** [comment]
@MahdiPishguy  `        fragNavController.popFragment();`
