### ISSUE TITLE
Using transactions with pushFragment

### ISSUE THREAD

**Issue by pishguy** [ncapdevi/FragNav#191]
how can i use simply transactions with `pushFragment` method? i can't find any sample code to know how can i implementing that

after use this code in one of fragments:

```
FragNavTransactionOptions.Builder transition = new FragNavTransactionOptions.Builder().addSharedElement(new Pair<>(view, transitionName));
fragmentNavigation.pushFragment(SampleFragment.createInstance(0), transition.build());
```

how can i get that on `SampleFragment` fragment to have animate moving this view to new place of `SampleFragment` fragment?

**Comment by ncapdevi** [comment]
Check the sample app.

**Comment by pishguy** [comment]
@ncapdevi in your sample code you use only `setDefaultTransactionOptions` code and its not my question, for example i want to make transition for image such as avatar or some TextView and you dont use this feature on sample
