### ISSUE TITLE
Marking the FragNavController open

### ISSUE THREAD

**Issue by nikhil-thakkar** [ncapdevi/FragNav#193]
I want to do some customisation on top of the current implementation.
Can you please mark the FragNavController class as open?

**Comment by erawhctim** [comment]
@nikhil-thakkar Sounds like you're better off just pulling in the library source as a gradle module and modifying it yourself

**Comment by nikhil-thakkar** [comment]
I changed my implementation in my code base for now. Seems to be working fine.
