### ISSUE TITLE
On Tab Reselected called in wrong time

### ISSUE THREAD

**Issue by KaeMs** [ncapdevi/FragNav#197]
I have 4 tabs, let's just call them A B C D, and A is my initial tab.

Here's the chronological order :
1. I press on B, onTabSelected gets called
2. I press back, I return to A
3. I press B again, I stay at A. Here, OnTabReselected is called.

Intuitively, it should call OnTabSelected again as I am at A right now, not calling B.
Why does it call OnTabReselected instead?

**Comment by ncapdevi** [comment]
You're talking about a different library. Please post any BottomBar issues there https://github.com/roughike/BottomBar

**Comment by KaeMs** [comment]
I am actually using the TabLayout from Android, lemme try that one called AHBottomNavigation real quick

**Comment by KaeMs** [comment]
Ok nevermind, when I changed to AHBN, the callback works really well!
