### ISSUE TITLE
Flickering screen while changing fragments through the FragNavBar

### ISSUE THREAD

**Issue by nadav2051** [ncapdevi/FragNav#198]
After the fragments has already been loaded, I still get a 'lag' which manifests in the form of a white screen for a split second while changing already loaded fragments.

I've tried searching and digging in a bit but can't seem to find a solution to this problem.

EDIT: I'm using the 2.4.0 Version of the library

**Comment by ncapdevi** [comment]
Try updating to 3.1.0. If you are still having issues, supply an example where I can replicate it and I'd be happy to take a look.
