### ISSUE TITLE
Go to root fragment from hidden stack

### ISSUE THREAD

**Issue by evgenybozhko2** [ncapdevi/FragNav#207]
How manage stack for hidden tab ? For example I want pop few levels back.

**Comment by ncapdevi** [comment]
Not sure that I understand the question, could you elaborate?

**Comment by evgenybozhko2** [comment]
Have you tried to thinking? (joke).
For example, we have two tabs with two stacks with hiding fragment strategy. When a user sees the first stack, the second one hidden. So I want to manage the hiden stack, for example, make a pop or go to root fragment into second not displayed stack. Does it possible?
Thanks

**Comment by ncapdevi** [comment]
You can clear a stack that is not currently selected via `fun clearStack(tabIndex: Int, transactionOptions: FragNavTransactionOptions? = defaultTransactionOptions)` other than that, operations can only be performed on the current stack. You may want to rethink your UX, as popping fragments on non-visible stack is very strange navigation UX.

**Comment by evgenybozhko2** [comment]
Thanks for the very long response. 
Nothing strange there, because it's a simple logout feature.

**Comment by VuHongKy** [comment]
@ncapdevi Please check this, bro and help me:
https://github.com/ncapdevi/FragNav/issues/233#issue-616415495
