### ISSUE TITLE
Different toolbar for each Fragment

### ISSUE THREAD

**Issue by hosseinaminii** [ncapdevi/FragNav#209]
How to add different toolbar for each Fragment? setSupportActionBar does not work correctly

**Comment by hossein-amini** [comment]
By changing  FragNavController.DETACH_ON_NAVIGATE_HIDE_ON_SWITCH to  FragNavController.DETACH the issue fixed, but I want to know, doesn't it cause any performance issue?

**Comment by hosseinaminii** [comment]
By changing FragNavController.DETACH_ON_NAVIGATE_HIDE_ON_SWITCH to FragNavController.DETACH the issue fixed, but I want to know, doesn't it cause any performance issue?

**Comment by ncapdevi** [comment]
Nope, it shouldn't cause any performance issues. But also `setSupportActionBar` should be working correctly. I'm not sure which lifecycle event you are using to set the support action bar, but the library has a normal fragment lifecycle, so it should definitely be doable.
