### ISSUE TITLE
Library in jcenter is outDated 

### ISSUE THREAD

**Issue by jmtt89** [ncapdevi/FragNav#22]
Hi, your library on jcenter don't have the last commits (Support For onSaveInstanceState)

**Comment by rgocal** [comment]
May have to fork this and rebuild this library

**Comment by ngoohebi** [comment]
Please fix it. Thank you!

**Comment by ncapdevi** [comment]
Sorry for delay. Library is now up to date, just use compile 'com.ncapdevi:frag-nav:1.1.0' and check out the change log for updates.
