### ISSUE TITLE
Specific refresh fragment.

### ISSUE THREAD

**Issue by murselsahin** [ncapdevi/FragNav#225]
My Hide Strategy:
`fragNavController.setFragmentHideStrategy(FragNavController.HIDE);`

Everything is OK but i want CartFragment not HIDE. When i push Cart icon , refresh cart fragment.

Is there any way ?

  switch (index) {
            case INDEX_HOME:
                return HomeFragment.newInstance();
            case INDEX_CAMPAIGNS:
                return CampaignFragment.newInstance("");
            case INDEX_CATEGORIES:
                return CategoryFragment.newInstance("0", getString(R.string.categories)); 
            case INDEX_SEARCH:
                return HomeFragment.newInstance(); //todo
            case INDEX_CART:
                return CartFragment.newInstance(); // i want refresh this fragment specific

        }

**Comment by ghost** [comment]
Hi, @murselsahin have you found the solution for this.
