### ISSUE TITLE
What's the proper way of creating Fragments for it to work?

### ISSUE THREAD

**Issue by koallen** [ncapdevi/FragNav#26]
Hi, I'm not a very experienced Android developer. I'm trying to use your library together with BottomBar for 3 Fragments.

The fragments are loaded. But it seems that it always stays on the first fragment. How should I create my fragments to make it work properly? Right now all 3 fragments extend that Fragment class from the Android support library.

**Comment by xstar97** [comment]
1. [tutorial 1](http://www.vogella.com/tutorials/AndroidFragments/article.html)
2. [tutorial 2](http://www.techotopia.com/index.php/Using_Fragments_in_Android_-_A_Worked_Example)
3. [tutorial 3](https://www.raywenderlich.com/117838/introduction-to-android-fragments-tutorial)
4. [tutorial 4](www.google.com)

**Comment by ncapdevi** [comment]
Please check the sample app for examples on how to switch between fragments. If you've gone through the sample app and still have specific questions, let me know.
