### ISSUE TITLE
How to delete actionBar with FragNav ?

### ISSUE THREAD

**Issue by jesuisnicolasdavid** [ncapdevi/FragNav#27]
i get back a white bar when trying to remove it ..

**Comment by Ibtihaaj** [comment]
Im getting same issue on HTC devices. Any solution please ? 
![htc 820 prevw](https://cloud.githubusercontent.com/assets/22816785/19643850/9390e558-99fd-11e6-903d-929ad6d7aa11.png)

**Comment by alouanemed** [comment]
Why do you wanna remove it ? and Did you solve this ?

**Comment by ncapdevi** [comment]
Not entirely sure why this would be happening. Could you give me some code that you're using to remove the bar?

**Comment by ncapdevi** [comment]
I don't believe that this has anything to do with the FragNav library, but if you can give me some more insight then I can look into it.
