### ISSUE TITLE
How to update library to last merge?

### ISSUE THREAD

**Issue by balkarov** [ncapdevi/FragNav#28]
Hello
Thank for your library. I use this `compile 'com.ncapdevi:frag-nav:1.0.3'`
But I want use last version with savedInstant and other fix 
https://github.com/ncapdevi/FragNav/pull/21

How can I use last merge?

**Comment by ncapdevi** [comment]
Sorry for delay. Library is now up to date, just use compile 'com.ncapdevi:frag-nav:1.1.0' and check out the change log for updates.
