### ISSUE TITLE
Please keep your releases in sync with your master branch

### ISSUE THREAD

**Issue by p-fischer** [ncapdevi/FragNav#31]
You already ran out of sync between releases and master branch again. That's quite annoying since I like to see a branch, which is in the same state as the current release. Otherwise, it's difficult to track the actual state of the release and look something up in the correct version of the sample app.

I'd suggest only merging to master if you make a release. Or alternatively, use a distinct release branch.

**Comment by ncapdevi** [comment]
Not going to do it that way. Release and master are in fact in sync with regards to the library. You can manage your own branches on a fork if you'd like, but this is not an issue.
