### ISSUE TITLE
How to animate the transition between fragments ?

### ISSUE THREAD

**Issue by prashantsharma24** [ncapdevi/FragNav#37]
I have used : -
`FragNavController.setTransitionMode(); `
but can't succeed. It's due to library or i am doing something wrong ,can't guess.
An error occurs stating that.
`Non-static method 'setTransition()' cannot be referenced from static context`
And i have also not found any example to show it's working state.
Can you assist me ?

**Comment by ncapdevi** [comment]
`setTransitionMode()` is not a static method so you need to use it from an instance of the FragNavController object.  
```
FragNavControler fragNavController = new FragNavController(savedInstanceState, getSupportFragmentManager(), R.id.container, fragments, INDEX_RECENTS);
fragNavController.setTransitionMode(FragmentTransaction.TRANSIT_FRAGMENT_FADE);
```
