### ISSUE TITLE
Fragment Transaction - Shared Elements, etc

### ISSUE THREAD

**Issue by liquidninja24** [ncapdevi/FragNav#41]
@ncapdevi: Great library!

I'm looking to implement FragNav into a single activity application with tabs, and was wondering if you'd given any thought to more complex transitions, or FragmentTransaction behavior in general? Specifically, I'm interested in utilizing shared element transitions as explained here: https://medium.com/@bherbst/fragment-transitions-with-shared-elements-7c7d71d31cbb#.y6g2ft1sv.

The immediate fix for this could be to overload the pushFragment and popFragment methods to allow passing in a `List` of `Pair`s of shared elements, but then you go down the slippery slope of adding new params for every property on a FragmentTransaction. To make things more extensible I thought about passing in a callback that takes in a FragmentTransaction and let's the caller modify properties on it before the FragNavController commits the transaction. This, however, opens up the possibility for a developer to completely screw themselves.

Do you have any thoughts on this?

Thanks!
Nick

**Comment by ncapdevi** [comment]
Hmm, this is a good one, thanks for taking the time to write it out.  Let me look into this a bit more and see if anything comes to mind, but I think you were spot on with both of your options as well as the possible cons.

**Comment by ncapdevi** [comment]
Spending a bit more time thinking about it, I'm especially hesitant abut the second option, and exposing the fragment transaction seems like an easy way for people to get tripped up.  I think you make a great point about the overflowing of arguments for a function, and definitely something I think is best if it can be avoided.  An alternative approach I think would to have and overload for each of the FragNav transactions that take in a custom object.   

Something like

```
public class FragNavFragment {
    Fragment fragment;
    List<Pair<View,String>> sharedElements;
    FragmentTransaction enterTransition;
    FragmentTransaction exitTransition;
    
    //Other elements we might want to through in here.
}
```
With overloads like:
```
    public void push(@Nullable FragNavFragment fragment) {
    }

```
(The name is horrible)
This would keep the function clean, and allow for a space to add additional elements in the future.  Doing it this way would keep all existing code functioning just fine, and add functionality for anyone that would want to use it.

Thoughts?

**Comment by liquidninja24** [comment]
Going with a separate class is probably the safest and most extensible approach. The only downside is that it requires updating whenever google update's their FragmentTransaction class, which probably won't be that often.

As for what to call the object and method overloading- it might make more sense create a FragmentTransaction options class and pass that in alongside the target fragment.  That way the interface is similar to what's there now, and those who want to provide options can just pass in an instance of the new class.

Something like this:

```
public class FragNavTransactionOptions {
    List<Pair<View, String>> sharedElements;
    @Transit
    int transition;
    @AnimatorRes
    int enterAnimationId;
     ...
}
```

Alternate names: `FragNavTransactionSettings`, `FragNavSettings`, ...

With methods:
```
public void pushFragment(@NotNull Fragment fragment);
public void pushFragment(@NotNull Fragment fragment, @Nullable FragNavTransactionOptions options);
...
```

What do you think?

**Comment by ncapdevi** [comment]
Yup, I definitely like that the most.  I think that strikes a nice balance. I'll go ahead and branch off, write up a version of it and it'd be a big help if you could check it and make sure it'd work for your use case.

**Comment by liquidninja24** [comment]
Sounds great. Thanks for being so responsive :)

I haven't integrated FragNav to the point where I need to use custom settings yet (just thinking ahead), but I'm happy to code review your PR and provide feedback.

**Comment by ncapdevi** [comment]
Thanks for your insight and thoughtful responses. Check out this [Branch 2.0.0](https://github.com/ncapdevi/FragNav/tree/v2.0.0) when you have the time. I've implemented but haven't actually tested yet.  I'll go through at some point and make sure it all works, but I think the logic holds.

**Comment by liquidninja24** [comment]
Do you wanna open a PR that I can make suggestions on, or should I just reply here with my thoughts?

**Comment by ncapdevi** [comment]
Feel free to open a PR and I'll look it over. Either works for me.

**Comment by liquidninja24** [comment]
Whenever you have some time: https://github.com/ncapdevi/FragNav/pull/42
