### ISSUE TITLE
Pushing a full screen fragment on click of a button inside on of the child fragments

### ISSUE THREAD

**Issue by infinitetrooper** [ncapdevi/FragNav#43]
Hi, 

Is there a way I can show a full screen sized fragment (like showing a full screen image for example) when a button is clicked on one of the child fragments?

I'm using Roughike's BottomBar along with FragNav.

Thank You

**Comment by ncapdevi** [comment]
Best bet in this situation would be to start a new full screen activity, and place the fragment inside of that. Hope this helps!
