### ISSUE TITLE
FragNavController initialization

### ISSUE THREAD

**Issue by liquidninja24** [ncapdevi/FragNav#44]
Hi Nick,

In attempting to integrate your library i've come across two issues that I was hoping you'd be able to fix.

First, the FravNavController constructor doesn't allow for passing in a TransactionListener, so when the initial fragment stack is selected the `listener.onTabTransaction` method is never invoked. This is because the `transactionListener` is null in the `initialize` function.

Second, I'm attempting to place the construction of the FragNavController in the `onCreate` function of a base activity. I'm running into issues where a child class instantiates some class variables that are needed by the root fragment, but since `getRootFragment(i)` is called immediately after instantiating the FragNavController my root fragment is created with null data; The child activity's `onCreate` hasn't had a chance to run yet. It would be great if we could set the starting index to `-1` so that no fragment is instantiated allowing us to call `switchTab` at a point when we're ready to show the initial fragment.

I hacked something together to verify it works, but would love for you to take a look at it since you know the library better than I do.

Thanks!
Nick

**Comment by liquidninja24** [comment]
I ended up creating a PR with some initial thoughts. Whether you use this PR or create your own, i'd be great to get this functionality integrated. If you're okay with these changes I'll add some unit tests.

PR: https://github.com/ncapdevi/FragNav/pull/45

**Comment by ncapdevi** [comment]
Saw these both with the PR and thought they were good. I'm going to have to go back through it and write up some unit tests, but hoping to push it out with version 2.0.0 of the library once it's all stable. I may re-evaluate the -1 index there. I need to think on it a bit to figure out the cleanest way to do all of that, but it definitely works for now. Also considering changing the initial constructor of the FragNavController to a builder, because those constructors are getting gross.

**Comment by liquidninja24** [comment]
I totally agree with you on wanting to find betters solutions to the `NO_TAB` and constructor issues. I actually didn't expect you to merge the PR outright, but just start the conversation.

With that in mind i've integrated version 2.0.0 into my application (fork), and would love to help you get a release out this weekend if possible so that I can use Gradle instead. I've started working on adding unit tests to help sure things up, but let me know how else I can help you out.

**Comment by ncapdevi** [comment]
Sounds great. I'll be out of town this weekend and avoiding working on stuff, but will finish up that Tab stuff, possible builder for the constructor, and fully test out the new stuff added sometime mid next week. Any pull requests for things that you add that fit the scope of the library would be great. Really appreciate the help.

**Comment by ncapdevi** [comment]
I added a lot of the stuff that we talked about and a bit more(All in Master right now). Now using a builder instead of a constructor.  Still need to sit on the `NO_TAB`  idea, but honestly, I'm not coming up with a more elegant way of handling it.  I think it's good to initialize it with no tab selected in general, as it allows for some more flexibility, but I'm still thinking on it a bit. Take a look if you have the time. I'll be trying to get 2.0.0 out by this weekend.

**Comment by liquidninja24** [comment]
The new constructor builder approach looks a lot more reasonable. Good call on that. Also, thank you for merging in my PRs! I'm sorry I haven't contributed to testing, but I've been pretty busy this week. I may jump in and add some tests this weekend, if not it'd still be nice to see 2.0.0 out. Thanks again for the hard work 👍

**Comment by ncapdevi** [comment]
Latest commit on master splits up builder and initialization. I think this is good for a few reasons. One, takes care of your NO_TAB issue(I think, maybe). You can create the object but initialize it wherever. Two, the callbacks (onTabTransaction or onFragmentTransaction) would get called during initialization but the FragNavController object itself hadn't been created yet, so you couldn't use it 
(you often need to know if it's the root fragment or not).  Let me know if this makes sense and works for you.

**Comment by liquidninja24** [comment]
Yep, exposing the `initialize` function so that it can be called separately works for me. The other optimizations you made (TransactionOptions) make sense as well 👍

**Comment by ncapdevi** [comment]
Awesome, you can check it out with your current project using `compile 'com.ncapdevi:frag-nav:2.0.0RC'`  I want to test it out a bit more and make sure all the dust has settled, and then I'll drop the RC and officially release.
