### ISSUE TITLE
Iterate through all fragments

### ISSUE THREAD

**Issue by codeteo** [ncapdevi/FragNav#57]
Hi,

is it possible to iterate through all fragments ? I know I can use `getCurrentStack()` and then loop for the `Fragment`s into the current stack but how can I access other stacks too?

Thanks!

**Comment by ncapdevi** [comment]
Hmm, definitely seems like a valid request.  I'm hoping to release 2.0 by next week at the latest with a bunch of features. I'll add a function that looks like

`public Stack<Fragment> getStack(int stackIndex);`

Would that work?

**Comment by codeteo** [comment]
> Would that work?

Yes, it would be great! Thanks again!

**Comment by ncapdevi** [comment]
👍   It's been added and is in the Master branch. Release coming by mid-next week
