### ISSUE TITLE
SharedElement Example

### ISSUE THREAD

**Issue by andanicalik** [ncapdevi/FragNav#62]
Can you add example about use shared element ? I add shared element and transition to FragNavTransactionOptions but animation doesn't shown.

**Comment by ncapdevi** [comment]
Hey @andanicalik  Can you show me the transactionOptions that you're building, how you're sending them in, and where you're trying to grab them?

Thanks

**Comment by andanicalik** [comment]
Hi. I added my code. Thank you for your interest @ncapdevi .

`FragNavTransactionOptions options = FragNavTransactionOptions.newBuilder()
.addSharedElement(new Pair<View, String>(viewHolder.imageViewExerciseCategory, "exerciseCategory")).transition(R.transition.exercise_category).build();`
        
`ExerciseSubCategoryFragment fragment = ExerciseSubCategoryFragment.newInstance(categoryId);
mFragmentNavigation.pushFragment(fragment, options);`

-> exercise_category.xml

`<transitionSet xmlns:android="http://schemas.android.com/apk/res/android"
    android:transitionOrdering="together">
    <changeBounds />
    <changeTransform />
    <changeImageTransform />
</transitionSet>`

**Comment by ediazest** [comment]
Hi @andanicalik, have you had any luck with this?

**Comment by ncapdevi** [comment]
What we really need is a PR for the sample app to have shared elements. If we can get that, it's easier to test.

**Comment by Thomas-Vos** [comment]
I have the same issue and can't get it to work. Could it be because this library uses `add(...)` instead of `replace(...)` for the fragment transaction?

**Comment by ncapdevi** [comment]
@Thomas-Vos Not entirely sure on that. I was under the impression that `add(...)`would work, but it's possible that it doesn't. What I really need is to have a solid sample app to test this out.

**Comment by Thomas-Vos** [comment]
@ncapdevi So what do you want to do? Do you want me to make a small sample app (using FragNav) and put it on GitHub? I've tried it, but cannot get it working, I think because of `add(...)`. Here are some related StackOverflow questions: https://stackoverflow.com/q/29145031/4583267, https://stackoverflow.com/q/29259829/4583267, https://stackoverflow.com/q/35052237/4583267.

**Comment by Thomas-Vos** [comment]
@ncapdevi Any idea how this could be fixed?
