### ISSUE TITLE
Use BottomNavigationView and Navigation Drawer Together

### ISSUE THREAD

**Issue by LinArcX** [ncapdevi/FragNav#65]
Hi and thanks for this great library.
its work  well when you just some limited tab in your application.
but when sometime anybody like to mix bottomNavigationView And Navigation Drawer, simultaneously.
i.e:I have 7 Fragment In Navigation Drawer And 4 Fragment In Bottom Navigationthe.
 FragNav just now accept up to 5 fragment and this Situation Cannot be handled Properly.
Is this situation can be changed, please?

**Comment by ncapdevi** [comment]
Duplicate of #63
