### ISSUE TITLE
hold fragment state after change it

### ISSUE THREAD

**Issue by mrzslr** [ncapdevi/FragNav#67]
hi.
i know that my question have no business to this library . but i didn't find a good answer for once of all.
i use bottom bar and 3 fragment with retrofit network call in each fragment . 
when i wanna change fragments(replace or whatever) it's lose data or reload network callbacks . i mean like fragment recreated.
so how can i fix it .i use onsavedInstanceState but there was no solution .

**Comment by ncapdevi** [comment]
This is a great library that should help you out https://github.com/frankiesardo/icepick
