### ISSUE TITLE
Custom popEnter/popExit Animations not working

### ISSUE THREAD

**Issue by drewlarsen** [ncapdevi/FragNav#69]
I've defined 4 animations enter, exit, popEnter, popExit. Before I migrated to this library, the animations were working correctly. When I try using them in this library (I added them as the defaults using the builder) for a "popFragment", the popEnter/popExit animations do not get used. Instead, the enter/exit animations get replayed.

As a test to see if I was using the library incorrectly, I modified the test "Bottom Drawers" app but the same thing happens there.

I've stepped through the library's code quite a bit, it looks like the animations are being set correctly, I can't find any obvious problem. I wonder though, because I never see popBackStack() ever being called, but rather some .remove() calls to get rid of fragments, maybe the animations are never triggered.

Any ideas?

**Comment by drewlarsen** [comment]
btw, this library is great and solves a tough problem, I hope that custom animations can be supported (or maybe I'm just doing it wrong)

**Comment by evgenybozhko2** [comment]
The same issue! Wait for the author reply.

**Comment by evgenybozhko2** [comment]
Found reason, why onBack navigation animation don't apply. It happen because when go back using 
[remove](https://developer.android.com/reference/android/app/FragmentTransaction.html#remove(android.app.Fragment)) and [replace](https://developer.android.com/reference/android/app/FragmentTransaction.html#replace(int,%20android.app.Fragment)) methods. But [setCustomAnimations](https://developer.android.com/reference/android/app/FragmentTransaction.html#setCustomAnimations(int,%20int,%20int,%20int)) method say: "Set specific animation resources to run for the fragments that are entering and exiting in this transaction. The popEnter and popExit animations will be played for enter/exit operations specifically when popping the back stack."

Here two way to fix it. I don't have time to pull request. Thanks.

**Comment by ncapdevi** [comment]
Two questions; 
Are the enter/exit (not the popEnter/popExit) animations working correctly?
 Is there a a reason that enter/exit animations need to be different from the popEnter/popExit?

**Comment by evgenybozhko2** [comment]
Yeah, enter and exit animation the same (exit like enter). So, custom exit animation don't work, at described above reasons. 

Yeah, many ways to must have different animation enter-exit. For example IOS default animation. Many times customers want IOS style animation. (from left to right - right to left) slide.

**Comment by ncapdevi** [comment]
I think there's some confusion. There are four different parameters `enter`, `exit`, `popEnter`, and `popExit`.  My question is do `enter` and `exit` work? If they do work, is there a reason for `enter` to be different than `popEnter`

**Comment by evgenybozhko2** [comment]
Yeah, enter and exit work correct. But popEnter and popExit use same animation for enter and exit. It's because when pop, lib use remove and add, methods.

**Comment by drewlarsen** [comment]
Hi Nic- thanks for looking into this issue. I like your library a lot, I was in the middle of building my own solution to this problem when I found yours! I'm looking to include it in the next update of my CrossFit fitness app: www.sugarwod.com

To clarify the issue, yes `enter` and `exit` both work as expected. And also yes the `popEnter` and `popExit` should be different.

For example, in my case I am looking to more or less duplicate the slide in/out animations that my app has on iOS. So:

enter = slide_in_from_right
exit = slide_out_to_left

popEnter = slide_in_from_left
popExit = slide_out_to_right

As smail2133 says, the enter/exit work correctly. But, instead of the popEnter/popExit being played (in a popFragment situation), the regular enter/exit animations are played.

I followed this SO answer to set up my animations (before I was using your lib) and everything worked correctly:
https://stackoverflow.com/questions/21026409/fragment-transaction-animation-slide-in-and-slide-out

I suspect that the popEnter/popExit animations are never being played because (I don't think) this lib ever calls popBackStack() type functions, instead it just .remove() fragments, which I'm guessing causes the enter/exit animations to be played.

Here are my 4 animation XMLs, note that they all just manipulate the "x" value in different ways to create the slide effect.

enter: slide_in_from_right.xml
```
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
    <translate
        android:duration="@android:integer/config_mediumAnimTime"
        android:fromXDelta="100%"
        android:fromYDelta="0%"
        android:interpolator="@android:anim/decelerate_interpolator"
        android:toXDelta="0%"
        android:toYDelta="0%" />
</set>
```
exit: slide_out_to_left
```
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
    <translate
        android:duration="@android:integer/config_mediumAnimTime"
        android:fromXDelta="0%"
        android:fromYDelta="0%"
        android:interpolator="@android:anim/decelerate_interpolator"
        android:toXDelta="-100%"
        android:toYDelta="0%" />
</set>
```

popEnter: slide_in_from_left.xml
```
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
    <translate
        android:duration="@android:integer/config_mediumAnimTime"
        android:fromXDelta="-100%"
        android:fromYDelta="0%"
        android:interpolator="@android:anim/decelerate_interpolator"
        android:toXDelta="0%"
        android:toYDelta="0%" />
</set>
```

popExit: slide_out_to_right
```
<?xml version="1.0" encoding="utf-8"?>
<set xmlns:android="http://schemas.android.com/apk/res/android">
    <translate
        android:duration="@android:integer/config_mediumAnimTime"
        android:fromXDelta="0%"
        android:fromYDelta="0%"
        android:interpolator="@android:anim/decelerate_interpolator"
        android:toXDelta="100%"
        android:toYDelta="0%" />
</set>
```

**Comment by ncapdevi** [comment]
Ah! Okay, @drewlarsen, 

> enter = slide_in_from_right
> exit = slide_out_to_left
> 
> popEnter = slide_in_from_left
> popExit = slide_out_to_right

That clarifies things quite a bit. It makes sense that things are not working that way currently(the whole value prop of this library is that it manages multiple backstacks, and thus doesn't use the default android backstack, meaning that those popanimations aren't being called), but let me look into a possible solution

**Comment by ncapdevi** [comment]
Also @drewlarsen if you end up using the library in your app, go ahead and through me a PR and I'll include it in the readme

**Comment by evgenybozhko2** [comment]
Possible way to fix animation behavior, you need accept only two animation int you transaction. Incapsulate the animation setup for some transaction enter or pop. So, library must apply two params with enter and exit and popEnter and popExit animations. So, and setup inner fragment transaction depended of the logic, go back or ahead. Thanks.

**Comment by ncapdevi** [comment]
I believe I have a solution that will work internally without having to change anything from the libraries API side, coding it up now and if it works, I can push it out a 2.0.2

**Comment by ncapdevi** [comment]
@drewlarsen @smail2133  I got it working and am pushing up a fix now. It will be version `compile 'com.ncapdevi:frag-nav:2.0.2'`  Also, for testing reasons, I used the slide animations that you were using, so if you have a fork of the library, you can test it and see it working when on the Navigation Drawer of the sample app

**Comment by drewlarsen** [comment]
It works! Thanks for the quick fix Nic. I'll let you know if anything else comes up in our beta testing and I'll be sure to do a PR for the readme. We're aiming to launch this version in about 2 weeks.

**Comment by drewlarsen** [comment]
hey Nic, looks like this latest released introduced a new bug:
https://github.com/ncapdevi/FragNav/issues/74
