### ISSUE TITLE
Switching tabs uses enter/exit animations

### ISSUE THREAD

**Issue by drewlarsen** [ncapdevi/FragNav#74]
using the latest 2.0.2 release

when the popEnter/popExit fix was added into 2.0.2, it looks like it introduced a new bug.

When switching among tabs, fragment animations are now being used. When switching tabs, there should be no animations (this worked previously in 2.0.1).

Here is my FragNav setup:

```
        mNavController = FragNavController.newBuilder(savedInstanceState, getSupportFragmentManager(), R.id.content_frame)
                .transactionListener(this)
                .defaultTransactionOptions(
                        FragNavTransactionOptions
                                .newBuilder()
                                .customAnimations(
                                        R.anim.slide_in_from_right,    // enterAnimation
                                        R.anim.slide_out_to_left,      // exitAnimation
                                        R.anim.slide_in_from_left,     // popEnterAnimation
                                        R.anim.slide_out_to_right      // popExitAnimation
                                )
                                .build()
                )
                .rootFragmentListener(this, TabType.COUNT.toInteger())
                .build();
```

Nothing changed in my code between 2.0.1 and 2.0.2 except adding in the 4 customAnimations above.

**Comment by ncapdevi** [comment]
Hey Drew, that's because the tab switching is using the default customAnimations, you can override this but using   ` public void switchTab(int index, @Nullable FragNavTransactionOptions transactionOptions)`  function and sending in whatever (or null) animations you want

**Comment by drewlarsen** [comment]
Thx Nic, that did the trick!

Weird that it wasn't necessary in 2.0.1, but maybe I made another change which I've forgotten.

**Comment by codeteo** [comment]
Hi Nic, I have a similar issue and settings `FragNavTransactionOptions` to `null` when calling `switchTab` didn't help.

I'm using version `2.4.0` of your library.

The code I'm using : 


        FragNavTransactionOptions options =
                FragNavTransactionOptions.newBuilder()
                .customAnimations(R.anim.anim_slide_in_left, R.anim.anim_slide_out_left, R.anim.anim_slide_in_right, R.anim.anim_slide_out_right)
                .build();

        navController =
            FragNavController.newBuilder(savedInstanceState, getSupportFragmentManager(), R.id.fl_patient_dashboard_content)
                .transactionListener(this)
                .rootFragmentListener(this, NUM_OF_TABS)
                .defaultTransactionOptions(options)
                .selectedTabIndex(INDEX_MEDICAL)
                .build();

  
and when I want to switch Tab : 

    @Override
    public void showManageTab() {
        navController.switchTab(INDEX_MANAGE, null);
    }

but adding `null` to `switchTab()` does not disables the animation when changing tabs. 
Unless this is not how it's supposed to be used

Thanks!

**Comment by chnouman** [comment]
Same issue adding null not helping.
