### ISSUE TITLE
How to clear root fragment?

### ISSUE THREAD

**Issue by sbfss** [ncapdevi/FragNav#75]
Hello,
In some cases I need to clear root fragments and clear stacks but method `getRootFragment(int i)` is called only once for each stack. Is it possible to clear root fragments?

**Comment by ncapdevi** [comment]
You can use the `replaceFragment` function?

**Comment by sbfss** [comment]
@ncapdevi Can you explain how to replace root fragments on each tabs? replaceFragment replace only current fragment.

**Comment by sbfss** [comment]
@ncapdevi any update?
