### ISSUE TITLE
Animate only on push/pop fragments and disable animation when switching between tabs

### ISSUE THREAD

**Issue by fernandospr** [ncapdevi/FragNav#79]
I have a BottomNavigationView and I'm using the following (copied from the sample app):

```
mNavController = FragNavController.newBuilder(savedInstanceState, getSupportFragmentManager(), R.id.container)
                        .rootFragments(fragments)
                        .defaultTransactionOptions(FragNavTransactionOptions.newBuilder().customAnimations(R.anim.slide_in_from_right, R.anim.slide_out_to_left, R.anim.slide_in_from_left, R.anim.slide_out_to_right).build())
                        .build();
```

This will animate push/pop fragments inside a tab, but also when switching between tabs. I would like to disable animations when switching between tabs (or do other animation, maybe fade in/out).

Is that possible?

**Comment by fernandospr** [comment]
I have figured out how to do it:

Instead of using `defaultTransactionOptions` I should pass `FragNavTransactionOptions.newBuilder().customAnimations` as an argument to the push/popFragment methods.

**Comment by chnouman** [comment]
@fernandospr  I'm still getting the error  this is how I'm doing this 
                

> .defaultTransactionOptions(FragNavTransactionOptions.newBuilder().customAnimations(R.anim.slide_in_from_right, R.anim.slide_out_to_left, R.anim.slide_in_from_left, R.anim.slide_out_to_right).build())

**Comment by fernandospr** [comment]
I'm using this:

```
private final FragNavTransactionOptions mTransactionOptions = FragNavTransactionOptions
            .newBuilder()
            .customAnimations(R.anim.enter_from_right,
                    R.anim.exit_to_left,
                    R.anim.enter_from_left,
                    R.anim.exit_to_right)
            .build();
```
To  push/pop with animation:
`mNavController.pushFragment(fragment, mTransactionOptions);`

To switch tabs:
`mNavController.switchTab(FragNavController.TAB2);`
