### ISSUE TITLE
[Question] How do we retain fragment instance state and use POP_BACK_STACK_INCLUSIVE?

### ISSUE THREAD

**Issue by ghost** [ncapdevi/FragNav#85]
First of all I want to say thanks for this library and the sample. While playing with the library I found out that my fragment states were not been restored from backstack, also there was no way of skipping some fragments in stack as it might be one of the many use cases that would be required by application. Is there a way to do it? If yes, can you provide details or examples? if no, can we expect an update from this library in future?

**Comment by ncapdevi** [comment]
There is a `popFragments(int depth)` method that allows for popping multiple fragments at once.


As far as fragment state not being restored, you should be handling that yourself via the `onSaveInstanceState()` method of the fragments.
