### ISSUE TITLE
Fragment Exist

### ISSUE THREAD

**Issue by microcian** [ncapdevi/FragNav#89]
Hi, man how may i detect fragment already in Stack or not ? if fragment is exist so rather than add new Instance , just show already added Fragment , help me to do this

**Comment by ncapdevi** [comment]
`public Stack<Fragment> getCurrentStack()` You can use this function, that will return the current stack and from there you can do whatever you need to to find if what you're looking for already exists.  It should be noted that this returns a clone of the stack, not the actual stack itself.

**Comment by microcian** [comment]
I've Created a function to detect fragment exist or not 

public boolean isFragmentExist(String fragmentTag) {
        boolean isExist = false;
        if(getCurrentStack() != null){
            for (Fragment fragment: getCurrentStack()) {
                if(fragment.getTag().contains(fragmentTag)){
                    isExist = true;
                    break;
                }
            }
        }

        return isExist;
    }


**But i am Stuck if isFragmentExist is true then no need to add this , just show **
**Exception is if you press a tab again and again ..it add fragment many time and press back you have to press back button many times **

**Comment by ncapdevi** [comment]
Nope, you won't be able to use the tag as the tag is unique and created during it's initial addition to the FragmentManager.  You'll need to add your own uniqueIdentifier to your fragment class and check against that. 

```
if (yourFragment.GetMyID() == fragmentYouMightWantToAdd.GetMyID()){
 return true;
}

```

Regardless, the problem itself is outside the scope of the library.

**Comment by microcian** [comment]
Okay but if we fragment is already added how would i prevent to add again
in stack ?
