### ISSUE TITLE
Reduce Dependencies: Replace appcompat-v7 with support-fragment

### ISSUE THREAD

**Issue by commonsguy** [ncapdevi/FragNav#91]
The `frag-nav` module declares a dependency on `appcompat-v7`, despite not using it. `support-fragment` should be sufficient to fulfill the imports, and that would make it simpler to use this library in an app that is not itself using `appcompat-v7`.

Thanks for considering this!

**Comment by ncapdevi** [comment]
@commonsguy  You appear to be correct. Will pull that out in the next version (couple other things need fixed so it should be shortly). Thanks for pointing this out!

**Comment by ncapdevi** [comment]
Fixed in [2.2.3](https://github.com/ncapdevi/FragNav/releases/tag/2.2.3)
