### ISSUE TITLE
Adding fragments to a different container layout

### ISSUE THREAD

**Issue by MostafaNasiri** [ncapdevi/FragNav#92]
Hi
First of all thank you for making this great library
In my app I have three tabs with three root fragments. Inside one of my root fragments I need to be able to add more fragments and that fragments should be added to the backstack related to the current root fragment but it seems it's not possible since I can only push fragments to one container layout with your library.
So the question is how can I add fragments to a specific backstack (lets say TAB1's backstack) but with a different container layout?
Thanks

**Comment by ncapdevi** [comment]
In that case you'll just want to create another instance of `FragNavController` that manages that new container layout. Then you can do whatever you want regarding that stack as well as the other controller's stack.

**Comment by MostafaNasiri** [comment]
Thanks. Any idea how to handle back button for that fragment?

**Comment by MostafaNasiri** [comment]
Thanks. So I create the second FragNavController inside my fragment's onViewCreated like this:
`
marketFragmentController = FragNavController.newBuilder(savedInstanceState,
                getChildFragmentManager(),
                R.id.market_fragment_container_framelayout)
                .rootFragment(new MarketHomeFragment())
                .build();
`
Does it make any problem since the fragment gets recreated every time the user switches tabs?
