### ISSUE TITLE
Clear Stack 

### ISSUE THREAD

**Issue by enizbilgin** [ncapdevi/FragNav#93]
How to clear stack with index ? 
**for example : clearStack(TAB3)**

**Comment by ncapdevi** [comment]
Would be fairly easy to add, but just out of curiosity, what is the use-case for clearing a stack that you aren't currently on?

**Comment by enizbilgin** [comment]
I have 3 tabs. I want to from second fragment in the first tab go to the first fragment in the third tab. Then when I pass the first or second tab, I want to switching to the first fragment in tab. 
If the second tab is remaining from the second fragment, I want to switching first fragment in that tab.

**Comment by ncapdevi** [comment]
My suggestion would just be to clear the stack when you switch to it for the time being, although this may be a feature that is added in a future release.
