### ISSUE TITLE
Error with configChanges IllegalStateException: Fragment has not been attached yet.

### ISSUE THREAD

**Issue by tebitoq** [ncapdevi/FragNav#95]
Hi, I have this configuration for the library but I facing a error when the devices rotates.  

```
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        this.fragNavController = FragNavController
                .newBuilder(savedInstanceState, this.fragmentManager, R.id.fragments_container)
                .rootFragmentListener(this, 5)
                .transactionListener(this)
                .selectedTabIndex(-1)
                .build();
    }
```

This is the error:
 _

> Caused by: java.lang.IllegalStateException: Fragment has not been attached yet.
>                                             at android.support.v4.app.Fragment.instantiateChildFragmentManager(Fragment.java:2308)
>                                             at android.support.v4.app.Fragment.getChildFragmentManager(Fragment.java:773)
>                                             at com.ncapdevi.fragnav.FragNavController.clearDialogFragment(FragNavController.java:454)
>                                             at com.ncapdevi.fragnav.FragNavController.initialize(FragNavController.java:519)
>                                             at com.ncapdevi.fragnav.FragNavController.<init>(FragNavController.java:109)
>                                             at com.ncapdevi.fragnav.FragNavController.<init>(FragNavController.java:35)
>                                             at com.ncapdevi.fragnav.FragNavController$Builder.build(FragNavController.java:1035)
>                                             at com.bizagi.smartphone.presentation.module.main.MainTabsActivity.onCreate(MainTabsActivity.java:36)
>                                             at com.bizagi.smartphone.presentation.module.main.MainActivity.onCreate(MainActivity.java:85)
>                                             at android.app.Activity.performCreate(Activity.java:6975)
>                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
>                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
>                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
>                                             at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4754) 
>                                             at android.app.ActivityThread.-wrap18(Unknown Source:0) 
>                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599) 
>                                             at android.os.Handler.dispatchMessage(Handler.java:105) 
>                                             at android.os.Looper.loop(Looper.java:164) 
>                                             at android.app.ActivityThread.main(ActivityThread.java:6541) 
>                                             at java.lang.reflect.Method.invoke(Native Method) 
>                                             at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
>                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

_ 

So, Let me know if I doing something wrong or is a know issue.

Regards.

**Comment by ClimberBear** [comment]
It's a known recurring bug. I have the same problem, using the support library android.support.v4.app.Fragment in version 26.1.0

Check the post in https://github.com/kejunxia/AndroidMvc/issues/72, 
and the bugs in 
https://issuetracker.google.com/issues/37000979
https://issuetracker.google.com/issues/37122334

I'm also trying to find a workaround. In my tests, if you don't use the support library (and use the native Fragment), it works (I don't use FragNav, is manual code all)
